import Footer from '@/components/base/Footer';
import Navbar from '@/components/base/Navbar';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='bg-light'>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
