import Footer from '@/components/base/Footer';
import Navbar from '@/components/base/Navbar';
import ThemeProviderWrapper from '@/components/base/ThemeProviderWrapper';
import './globals.css';

export const metadata = {
  title: 'ClickNCart E-Commerce Shop',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='bg-light'>
        <ThemeProviderWrapper>
          <Navbar />
          {children}
          <Footer />
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
